### ISSUE TITLE
Implement Isometric Design System with Interactive Features

### ISSUE THREAD

**Issue by smaedala** [smaedala/t2l#1]
## Design System Modernization

Based on the T2L isometric logo design <img alt="image2" width="655" src="https://github.com/user-attachments/assets/3e326bae-c42b-4d80-a7f7-ad050c44989e" />, implementing a comprehensive design update with modern features and interactions.

### 1. Updated Color System & Isometric Design

```css
:root {
  /* Core Brand Colors */
  --t2l-blue-primary: #47b3e6;    /* Main blue from logo */
  --t2l-green-secondary: #34c759; /* Vibrant green accent */
  --t2l-red-accent: #e74c3c;     /* Dynamic red highlight */
  
  /* Extended Color Palette */
  --t2l-blue-light: #7cc9ef;
  --t2l-green-light: #6dd88d;
  --t2l-red-light: #ef776a;
  --t2l-background: #f8fafc;
  
  /* Shadows & Effects */
  --t2l-shadow-sm: 0 2px 4px rgba(71, 179, 230, 0.1);
  --t2l-shadow-lg: 0 8px 24px rgba(71, 179, 230, 0.15);
}
```

#### Navigation & Header
```css
.navbar {
  background: linear-gradient(135deg, 
    rgba(71, 179, 230, 0.95), 
    rgba(52, 199, 89, 0.95));
  backdrop-filter: blur(12px);
  transform: perspective(1000px);
}

.nav-item {
  transition: transform 0.3s ease;
}

.nav-item:hover {
  transform: translateZ(10px);
}
```

#### Hero Section with Isometric Grid
```css
.hero-grid {
  position: relative;
  perspective: 1000px;
}

.hero-tile {
  transform: rotateX(60deg) rotateZ(-45deg);
  background: var(--t2l-blue-primary);
  transition: transform 0.4s ease;
}

.hero-tile:hover {
  transform: rotateX(60deg) rotateZ(-45deg) translateZ(20px);
}
```

#### Animated Policy Cards
```css
.policy-card {
  position: relative;
  background: var(--t2l-background);
  transform-style: preserve-3d;
  transition: all 0.5s ease;
}

.policy-card::before {
  content: '';
  position: absolute;
  inset: 0;
  background: linear-gradient(135deg,
    var(--t2l-blue-primary),
    var(--t2l-green-secondary));
  opacity: 0;
  transition: opacity 0.3s ease;
}

.policy-card:hover {
  transform: translateZ(20px);
}
```

#### Dynamic Timeline Component
```javascript
class TimelineComponent {
  constructor() {
    this.items = document.querySelectorAll('.timeline-item');
    this.observer = new IntersectionObserver(
      (entries) => {
        entries.forEach(entry => {
          if (entry.isIntersecting) {
            entry.target.classList.add('timeline-item--active');
          }
        });
      },
      { threshold: 0.5 }
    );
  }

  init() {
    this.items.forEach(item => this.observer.observe(item));
  }
}
```

#### Isometric Menu Navigation
- 3D transformed menu items
- Hover state animations
- Dynamic color transitions

#### Interactive Policy Explorer
- Isometric grid layout
- Color-coded policy categories
- 3D rotation on hover

### 5. Mobile-First Adaptations

- Responsive isometric grids
- Touch-friendly interactions
- Simplified 3D effects for performance

### 6. Implementation Timeline

1. **Phase 1: Core Styling (Week 1-2)**
   - Implement new color system
   - Update typography and spacing
   - Add base animations

2. **Phase 2: Components (Week 3-4)**
   - Build isometric grid system
   - Create interactive cards
   - Implement timeline component

3. **Phase 3: Features (Week 5-6)**
   - Add 3D navigation
   - Build policy explorer
   - Implement mobile optimizations

### Technical Requirements

- CSS Custom Properties
- CSS Transform 3D
- Intersection Observer API
- Touch Events API

### Success Metrics

- Improved visual engagement
- Increased interaction time
- Better mobile usability
- Consistent brand experience

### Assets Needed

- SVG patterns for backgrounds
- Optimized images for isometric grid
- Icon set in brand colors
- <img alt="image2" width="655" src="https://github.com/user-attachments/assets/3e326bae-c42b-4d80-a7f7-ad050c44989e" /> - Reference for isometric design and color scheme

### Browser Support

- Modern evergreen browsers
- Fallbacks for older browsers
- Progressive enhancement approach
